name = "planbot"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[queues.producers]]
queue = "planbot-jobs"
binding = "PLANBOT_QUEUE"

[[queues.consumers]]
queue = "planbot-jobs"
max_batch_size = 1
max_retries = 2

[[kv_namespaces]]
binding = "PLANBOT_CONFIG"
id = "8d99f2ecde26429eb756a4ba278d1eec"

[[kv_namespaces]]
binding = "PLANBOT_CHAT"
id = "3e5fefb521174a1c950f9f005b966a45"

[[r2_buckets]]
binding = "PLANBOT_FILES"
bucket_name = "planbot-files"

[triggers]
crons = ["0 7,8,9 * * 1-5"]
